/**
 * Comprehensive dog breed list (~350 entries).
 * Sources: AKC (205 breeds, 2026), FCI, UKC, The Kennel Club UK, plus popular designer breeds and common shelter mix labels.
 * Sorted alphabetically for binary-search-friendly autocomplete.
 */
export const DOG_BREEDS: string[] = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akbash',
  'Akita',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'American Bulldog',
  'American English Coonhound',
  'American Eskimo Dog',
  'American Foxhound',
  'American Hairless Terrier',
  'American Pit Bull Terrier',
  'American Pit Bull Terrier Mix',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepherd',
  'Appenzeller Sennenhund',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Shepherd Mix',
  'Australian Stumpy Tail Cattle Dog',
  'Australian Terrier',
  'Aussiedoodle',
  'Aussiepoo',
  'Azawakh',
  'Barbet',
  'Basenji',
  'Basset Bleu de Gascogne',
  'Basset Fauve de Bretagne',
  'Basset Hound',
  'Bavarian Mountain Scent Hound',
  'Beagle',
  'Beagle Mix',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Laekenois',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bergamasco Sheepdog',
  'Berger Picard',
  'Bernedoodle',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Biewer Terrier',
  'Black and Tan Coonhound',
  'Black Mouth Cur',
  'Black Russian Terrier',
  'Bloodhound',
  'Blue Lacy',
  'Blue Picardy Spaniel',
  'Bluetick Coonhound',
  'Boerboel',
  'Bolognese',
  'Border Collie',
  'Border Collie Mix',
  'Border Terrier',
  'Bordoodle',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxador',
  'Boxer',
  'Boxer Mix',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Braque du Bourbonnais',
  'Briard',
  'Brittany',
  'Broholmer',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Canadian Eskimo Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Carolina Dog',
  'Catahoula Leopard Dog',
  'Caucasian Shepherd Dog',
  'Cavachon',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Central Asian Shepherd Dog',
  'Cesky Terrier',
  'Chesapeake Bay Retriever',
  'Chi-Poo',
  'Chihuahua',
  'Chihuahua Mix',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chinook',
  'Chiweenie',
  'Chorkie',
  'Chow Chow',
  "Cirneco dell'Etna",
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Cocker Spaniel Mix',
  'Collie',
  'Corgipoo',
  'Coton de Tulear',
  'Croatian Sheepdog',
  'Curly-Coated Retriever',
  'Czechoslovakian Vlcak',
  'Dachshund',
  'Dachshund Mix',
  'Dalmadoodle',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Danish-Swedish Farmdog',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Dorgi',
  'Double Doodle',
  'Drentsche Patrijshond',
  'Drever',
  'Dutch Shepherd',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mountain Dog',
  'Estrela Mountain Dog',
  'Eurasier',
  'Field Spaniel',
  'Fila Brasileiro',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'French Bulldog',
  'French Spaniel',
  'Frenchton',
  'German Longhaired Pointer',
  'German Pinscher',
  'German Shepherd',
  'German Shepherd Mix',
  'German Shorthaired Pointer',
  'German Spitz',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Goberian',
  'Goldador',
  'Golden Retriever',
  'Golden Retriever Mix',
  'Goldendoodle',
  'Gordon Setter',
  'Grand Basset Griffon Vendeen',
  'Great Dane',
  'Great Dane Mix',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greenland Dog',
  'Greyhound',
  'Hamiltonstovare',
  'Harrier',
  'Havanese',
  'Havapoo',
  'Hokkaido',
  'Hovawart',
  'Husky Mix',
  'Huskydoodle',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Doodle',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Jack-a-Poo',
  'Japanese Chin',
  'Japanese Spitz',
  'Jindo',
  'Kai Ken',
  'Karelian Bear Dog',
  'Keeshond',
  'Kerry Blue Terrier',
  'Kishu Ken',
  'Komondor',
  'Kromfohrlander',
  'Kuvasz',
  'Lab Mix',
  'Labradoodle',
  'Labrador Retriever',
  'Labsky',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Landseer',
  'Leonberger',
  'Lhasa Apso',
  'Lhasapoo',
  'Lowchen',
  'Maltese',
  'Maltipoo',
  'Manchester Terrier',
  'Maremma Sheepdog',
  'Mastiff',
  'Mastiff Mix',
  'McNab',
  'Miniature American Shepherd',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Mixed Breed',
  'Morkie',
  'Mountain Cur',
  'Mudi',
  'Munsterlander',
  'Neapolitan Mastiff',
  'Nederlandse Kooikerhondje',
  'Newfoundland',
  'Newfypoo',
  'Norfolk Terrier',
  'Norrbottenspets',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Parson Russell Terrier',
  'Patterdale Terrier',
  'Peekapoo',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Perro de Presa Canario',
  'Peruvian Inca Orchid',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Plott Hound',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomapoo',
  'Pomeranian',
  'Pomeranian Mix',
  'Pomsky',
  'Poochon',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Porcelaine',
  'Portuguese Podengo',
  'Portuguese Podengo Pequeno',
  'Portuguese Water Dog',
  'Pug',
  'Pug Mix',
  'Puggle',
  'Puli',
  'Pumi',
  'Pyrenean Mastiff',
  'Pyrenean Shepherd',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Romanian Mioritic Shepherd Dog',
  'Rottweiler',
  'Rottweiler Mix',
  'Russell Terrier',
  'Russian Toy',
  'Russian Tsvetnaya Bolonka',
  'Saint Berdoodle',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schapendoes',
  'Schipperke',
  'Schnoodle',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Segugio Italiano',
  'Sheepadoodle',
  'Shepsky',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Shih Tzu Mix',
  'Shih-Poo',
  'Shikoku',
  'Shorkie',
  'Siberian Husky',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Slovakian Wirehaired Pointer',
  'Small Munsterlander',
  'Smooth Fox Terrier',
  'Soft Coated Wheaten Terrier',
  'South Russian Ovcharka',
  'Spanish Mastiff',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Springador',
  'Springerdoodle',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Lapphund',
  'Swedish Vallhund',
  'Taiwan Dog',
  'Teddy Roosevelt Terrier',
  'Thai Ridgeback',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tornjak',
  'Tosa',
  'Toy Fox Terrier',
  'Transylvanian Hound',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Unknown',
  'Vizsla',
  'Volpino Italiano',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Westiepoo',
  'Wetterhoun',
  'Whippet',
  'White Swiss Shepherd Dog',
  'Whoodle',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Working Kelpie',
  'Xoloitzcuintli',
  'Yakutian Laika',
  'Yorkshire Terrier',
  'Yorkshire Terrier Mix',
  'Yorkipoo',
];
