import { useRef, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
  type NativeScrollEvent,
  type NativeSyntheticEvent,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuthStore } from '../src/stores/authStore';
import { supabase } from '../src/lib/supabase';
import { COLORS, FONT_SIZES, SPACING, BORDER_RADIUS, MIN_TOUCH_TARGET } from '../src/constants/theme';
import { LEGAL } from '../src/constants/config';

const TOS_TEXT = `TERMS OF SERVICE — PawCheck

Last Updated: ${LEGAL.TERMS_VERSION}

IMPORTANT: Please read these Terms of Service carefully before using PawCheck.

1. EDUCATIONAL PURPOSE ONLY

PawCheck provides EDUCATIONAL INFORMATION about dog health. It is NOT a substitute for professional veterinary advice, diagnosis, or treatment. PawCheck does NOT establish a veterinarian-client-patient relationship (VCPR).

2. NOT VETERINARY MEDICINE

The urgency classifications provided by PawCheck (Emergency, Urgent, Soon, Low Urgency) are educational guidance only. They are generated by artificial intelligence and may not account for all factors relevant to your dog's health. Always consult a licensed veterinarian for medical decisions.

3. EMERGENCY SITUATIONS

If you believe your dog is experiencing a medical emergency, contact your veterinarian or an emergency animal hospital immediately. Do not rely solely on this app in emergency situations.

4. AI-GENERATED CONTENT

PawCheck uses artificial intelligence to analyze symptoms you describe. AI-generated content may contain errors or inaccuracies. The information provided should be used as a starting point for discussion with your veterinarian, not as a definitive medical assessment.

5. DATA PRIVACY

We collect and process information you provide (dog profiles, symptom descriptions) to deliver our service. Symptom descriptions are sent to third-party AI providers for processing. For full details, see our Privacy Policy.

6. USER RESPONSIBILITIES

You agree to:
- Provide accurate information about your dog
- Not rely solely on PawCheck for medical decisions
- Seek professional veterinary care when needed
- Use the app only for dogs (not other animals or humans)

7. LIMITATION OF LIABILITY

PawCheck and its creators shall not be liable for any damages arising from your use of or reliance on information provided by the app. This includes, without limitation, any harm to your pet resulting from decisions made based on app-generated content.

8. AGE REQUIREMENT

You must be at least 13 years old to use PawCheck.

9. ACCOUNT DELETION

You may delete your account at any time through the app settings. Account deletion is permanent and cannot be reversed.

10. CHANGES TO TERMS

We may update these Terms of Service from time to time. Continued use after changes constitutes acceptance of the new terms.

By tapping "I Agree," you acknowledge that you have read, understood, and agree to these Terms of Service.`;

export default function Terms() {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [isChecked, setIsChecked] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  const user = useAuthStore((s) => s.user);
  const checkTermsAcceptance = useAuthStore((s) => s.checkTermsAcceptance);

  const handleScroll = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { layoutMeasurement, contentOffset, contentSize } = e.nativeEvent;
    const isAtBottom =
      layoutMeasurement.height + contentOffset.y >= contentSize.height - 50;
    if (isAtBottom) {
      setHasScrolledToBottom(true);
    }
  };

  const handleAccept = async () => {
    if (!user) return;

    setError('');
    setIsSubmitting(true);

    try {
      const { error: dbError } = await supabase
        .from('user_acknowledgments')
        .insert({
          user_id: user.id,
          terms_version: LEGAL.TERMS_VERSION,
        });

      if (dbError) throw dbError;
      await checkTermsAcceptance();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : 'Failed to record acceptance.'
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const canAccept = hasScrolledToBottom && isChecked;

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.container}>
        <Text style={styles.header}>Terms of Service</Text>
        <Text style={styles.scrollHint}>
          Please read and scroll to the bottom
        </Text>

        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          onScroll={handleScroll}
          scrollEventThrottle={200}
        >
          <Text style={styles.tosText}>{TOS_TEXT}</Text>
        </ScrollView>

        <View style={styles.footer}>
          <Pressable
            style={styles.checkboxRow}
            onPress={() => hasScrolledToBottom && setIsChecked((c) => !c)}
            disabled={!hasScrolledToBottom}
            accessibilityRole="checkbox"
            accessibilityState={{ checked: isChecked }}
            accessibilityLabel="I have read and agree to the Terms of Service"
          >
            <View
              style={[
                styles.checkbox,
                isChecked && styles.checkboxChecked,
                !hasScrolledToBottom && styles.checkboxDisabled,
              ]}
            >
              {isChecked && <Text style={styles.checkmark}>✓</Text>}
            </View>
            <Text
              style={[
                styles.checkboxLabel,
                !hasScrolledToBottom && styles.labelDisabled,
              ]}
            >
              I have read and agree to the Terms of Service
            </Text>
          </Pressable>

          {error ? (
            <Text style={styles.error} accessibilityRole="alert">
              {error}
            </Text>
          ) : null}

          <Pressable
            style={({ pressed }) => [
              styles.acceptButton,
              pressed && canAccept && styles.buttonPressed,
              !canAccept && styles.buttonDisabled,
            ]}
            onPress={handleAccept}
            disabled={!canAccept || isSubmitting}
            accessibilityRole="button"
            accessibilityLabel="Accept terms of service"
          >
            <Text style={styles.acceptText}>
              {isSubmitting ? 'Accepting...' : 'I Agree'}
            </Text>
          </Pressable>
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
    padding: SPACING.md,
  },
  header: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: '700',
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: SPACING.xs,
  },
  scrollHint: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: SPACING.md,
  },
  scrollView: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scrollContent: {
    padding: SPACING.md,
  },
  tosText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textPrimary,
    lineHeight: 22,
  },
  footer: {
    paddingTop: SPACING.md,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: MIN_TOUCH_TARGET,
    marginBottom: SPACING.md,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 2,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
  },
  checkboxDisabled: {
    borderColor: COLORS.textDisabled,
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  checkboxLabel: {
    flex: 1,
    fontSize: FONT_SIZES.sm,
    color: COLORS.textPrimary,
  },
  labelDisabled: {
    color: COLORS.textDisabled,
  },
  error: {
    color: COLORS.error,
    fontSize: FONT_SIZES.sm,
    marginBottom: SPACING.sm,
  },
  acceptButton: {
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    alignItems: 'center',
    minHeight: MIN_TOUCH_TARGET,
    justifyContent: 'center',
  },
  buttonPressed: {
    opacity: 0.8,
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  acceptText: {
    color: '#FFFFFF',
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
  },
});
